Imports System.Text
Imports System.Xml

Namespace LibSRI
  Public Class info
    Public Function claveAcceso(ByVal cod_unidad As String, ByVal id_comprobante As String, ByVal tipo_ambiente As String, ByVal tipo_emision As String, ByVal fec_emision As String, ByVal ruc As String, ByVal serie As String, ByVal secuencial As String) As String
      Dim codigo As Long = 1, i As Long
      Dim aux As Integer = 1, total As Integer = 0, modulo11 As Integer = 0
      Dim code As Integer() = {7, 1, 7, 2, 7, 3, 7, 4, 7, 5}
      Dim codemodulo As Integer() = {7, 6, 5, 4, 3, 2, 7, 6, 5, 4, 3, 2, 7, 6, 5, 4, 3, 2, 7, 6, 5, 4, 3, 2, 7, 6, 5, 4, 3, 2, 7, 6, 5, 4, 3, 2, 7, 6, 5, 4, 3, 2, 7, 6, 5, 4, 3, 2}
      If serie(2) <= "0"c Then aux = 2 Else aux = 3
      For i = 0 To code.Length - 1
        If ruc(i) <> "0"c Then codigo = (codigo * (code(i) * Convert.ToInt32(ruc(i) + String.Empty) * aux)) + Convert.ToInt32(cod_unidad) * 7
      Next

      Dim clavex As String = fec_emision.Substring(0, 2) & fec_emision.Substring(3, 2)
      Dim clave As String = ""
      clave = fec_emision
      clave = clave & id_comprobante
      clave = clave & ruc
      clave = clave & tipo_ambiente
      clave = clave & serie
      clave = clave & secuencial
      clave = clave & Convert.ToString(codigo).Substring(1, 8)
      clave = clave & tipo_emision

      For i = 0 To codemodulo.Length - 1
        total = total + (codemodulo(i) * Convert.ToInt32(clave(i) + String.Empty))
      Next

      modulo11 = 11 - (total Mod 11)
      If modulo11 = 10 Then
        Return clave & "1"
      ElseIf modulo11 = 11 Then
        Return clave & "0"
      Else
        Return clave & modulo11.ToString()
      End If
    End Function

    Public Sub GeneraXMLFactura(ByVal datosfact As DataTableReader, ByVal dtDet As DataTableReader)
      Dim wr As XmlTextWriter = New XmlTextWriter("C:\phoenix\Facturas\factnosigned.xml", Encoding.GetEncoding("UTF-8"))
      wr.WriteStartDocument(True)
      wr.Formatting = Formatting.Indented
      wr.Indentation = 2
      wr.WriteStartElement("factura")
      wr.WriteStartAttribute("id")
      wr.WriteString("comprobante")
      wr.WriteEndAttribute()
      wr.WriteStartAttribute("version")
      wr.WriteString("1.0.0")
      wr.WriteEndAttribute()
      While datosfact.Read()
        wr.WriteStartElement("infoTributaria")
        wr.WriteStartElement("ambiente")
        wr.WriteString(datosfact("tipoambienteid").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("tipoEmision")
        wr.WriteString(datosfact("tipoemisionid").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("razonSocial")
        wr.WriteString(datosfact("razonSocial").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("nombreComercial")
        wr.WriteString(datosfact("nombreComercial").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("ruc")
        wr.WriteString(datosfact("num_ruc").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("claveAcceso")
        wr.WriteString(datosfact("clave_acceso").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("codDoc")
        wr.WriteString(datosfact("codigo_doc").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("estab")
        wr.WriteString(datosfact("codigo_establecimiento").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("ptoEmi")
        wr.WriteString(datosfact("serie_doc").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("secuencial")
        wr.WriteString(datosfact("num_doc").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("dirMatriz")
        wr.WriteString(datosfact("dirMatriz").ToString())
        wr.WriteEndElement()
        wr.WriteEndElement()
        wr.WriteStartElement("infoFactura")
        wr.WriteStartElement("fechaEmision")
        wr.WriteString(datosfact("fecha_emision").ToString().Substring(0, 10))
        wr.WriteEndElement()
        wr.WriteStartElement("dirEstablecimiento")
        wr.WriteString(datosfact("dirEstablecimiento").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("contribuyenteEspecial")
        wr.WriteString(datosfact("contri_especial").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("obligadoContabilidad")
        wr.WriteString(datosfact("obl_conta").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("tipoIdentificacionComprador")
        wr.WriteString(datosfact("tipo_doc_cliente").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("razonSocialComprador")
        wr.WriteString(datosfact("nom_cliente").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("identificacionComprador")
        wr.WriteString(datosfact("num_doc_cliente").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("totalSinImpuestos")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosfact("total_sinImpuesto").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("totalDescuento")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosfact("total_descuento").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("totalConImpuestos")
        SumTipoImpuestoIVA(wr, datosfact("codigo_establecimiento").ToString(), datosfact("serie_doc").ToString(), datosfact("num_doc").ToString(), dtDet)
        wr.WriteEndElement()
        wr.WriteStartElement("propina")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosfact("propina_10").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("importeTotal")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosfact("valorTotal").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("moneda")
        wr.WriteString("DOLAR")
        wr.WriteEndElement()
        wr.WriteEndElement()
        wr.WriteStartElement("detalles")
        CreaDetalleFactura(wr, datosfact("codigo_establecimiento").ToString(), datosfact("serie_doc").ToString(), datosfact("num_doc").ToString(), dtDet)
        wr.WriteEndElement()

        'INFO ADICIONAL
        wr.WriteStartElement("infoAdicional")

        'INFO ADICIONAL DATOS CLIENTE
        wr.WriteStartElement("campoAdicional")
        wr.WriteStartAttribute("nombre")
        wr.WriteString("Dirección: ")
        wr.WriteEndAttribute()
        wr.WriteString(datosfact("direccion_cliente").ToString())
        wr.WriteEndElement()

        wr.WriteStartElement("campoAdicional")
        wr.WriteStartAttribute("nombre")
        wr.WriteString("Teléfono: ")
        wr.WriteEndAttribute()
        wr.WriteString(datosfact("telefono_cliente").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("campoAdicional")
        wr.WriteStartAttribute("nombre")
        wr.WriteString("E-mail: ")
        wr.WriteEndAttribute()
        wr.WriteString(datosfact("email_cliente").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("campoAdicional")
        wr.WriteStartAttribute("nombre")
        wr.WriteString("Periodo Lectivo: ")
        wr.WriteEndAttribute()
        wr.WriteString(datosfact("periodo").ToString())
        wr.WriteEndElement()
        wr.WriteEndElement()
      End While

      wr.WriteEndElement()
      wr.WriteEndDocument()
      wr.Close()
    End Sub

    Public Sub SumTipoImpuestoIVA(ByVal wr As XmlTextWriter, ByVal num_estab_fact As String, ByVal p_fact As String, ByVal secuencial_fact As String, ByVal datosdetfact As DataTableReader)
      While datosdetfact.Read()
        wr.WriteStartElement("totalImpuesto")
        wr.WriteStartElement("codigo")
        wr.WriteString("2")
        wr.WriteEndElement()
        wr.WriteStartElement("codigoPorcentaje")
        wr.WriteString(datosdetfact("cod_tarifa_iva").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("baseImponible")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("baseImponible").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("valor")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("valoriva12").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteEndElement()
      End While
    End Sub

    Public Sub CreaDetalleFactura(ByVal wr As XmlTextWriter, ByVal num_estab_fact As String, ByVal p_fact As String, ByVal secuencial_fact As String, ByVal datosdetfact As DataTableReader)
      While datosdetfact.Read()
        wr.WriteStartElement("detalle")
        wr.WriteStartElement("codigoPrincipal")
        wr.WriteString(datosdetfact("itemid").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("codigoAuxiliar")
        wr.WriteString(datosdetfact("cod_auxiliar").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("descripcion")
        wr.WriteString(datosdetfact("descripcion").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("cantidad")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("cantidad").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("precioUnitario")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("valor_unitario").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("descuento")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("descuento").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("precioTotalSinImpuesto")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("subtotal_0").ToString()) + Convert.ToDouble(datosdetfact("subtotal_12").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        If datosdetfact("descripcion2").ToString() <> String.Empty OrElse datosdetfact("descripcion3").ToString() <> String.Empty Then
          wr.WriteStartElement("detallesAdicionales")
          If datosdetfact("descripcion2").ToString() <> String.Empty Then
            wr.WriteStartElement("detAdicional")
            wr.WriteStartAttribute("nombre")
            wr.WriteString(datosdetfact("descripcion2").ToString())
            wr.WriteStartAttribute("valor")
            wr.WriteString("Detalle1")
            wr.WriteEndAttribute()
            wr.WriteEndElement()
          End If

          If datosdetfact("descripcion3").ToString() <> String.Empty Then
            wr.WriteStartElement("detAdicional")
            wr.WriteStartAttribute("nombre")
            wr.WriteString(datosdetfact("descripcion3").ToString())
            wr.WriteStartAttribute("valor")
            wr.WriteString("Detalle2")
            wr.WriteEndAttribute()
            wr.WriteEndElement()
          End If

          wr.WriteEndElement()
        End If

        wr.WriteStartElement("impuestos")
        wr.WriteStartElement("impuesto")
        wr.WriteStartElement("codigo")
        wr.WriteString(datosdetfact("cod_iva").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("codigoPorcentaje")
        wr.WriteString(datosdetfact("cod_tarifa_iva").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("tarifa")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("valor").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("baseImponible")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("subtotal_0").ToString()) + Convert.ToDouble(datosdetfact("subtotal_12").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("valor")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("iva_12").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteEndElement()
        wr.WriteEndElement()
        wr.WriteEndElement()
      End While
    End Sub

    Public Sub GeneraXMLNotaCredito(ByVal num_estab_fact As String, ByVal p_fact As String, ByVal secuencial_fact As String, ByVal datosfact As DataTableReader, ByVal datosdetfact As DataTableReader)
      Dim wr As XmlTextWriter = New XmlTextWriter("C:\phoenix\NotasCredito\factnosigned.xml", Encoding.GetEncoding("UTF-8"))
      wr.WriteStartDocument(True)
      wr.Formatting = Formatting.Indented
      wr.Indentation = 2
      wr.WriteStartElement("notaCredito")
      wr.WriteStartAttribute("id")
      wr.WriteString("comprobante")
      wr.WriteEndAttribute()
      wr.WriteStartAttribute("version")
      wr.WriteString("1.0.0")
      wr.WriteEndAttribute()
      While datosfact.Read()
        wr.WriteStartElement("infoTributaria")
        wr.WriteStartElement("ambiente")
        wr.WriteString(datosfact("cod_tipo_ambiente").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("tipoEmision")
        wr.WriteString(datosfact("cod_tipo_emision").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("razonSocial")
        wr.WriteString(datosfact("cod_ruc").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("nombreComercial")
        wr.WriteString(datosfact("cod_colegio").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("ruc")
        wr.WriteString(datosfact("cod_ruc").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("claveAcceso")
        wr.WriteString(datosfact("clave_acceso").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("codDoc")
        wr.WriteString("04")
        wr.WriteEndElement()
        wr.WriteStartElement("estab")
        wr.WriteString(num_estab_fact)
        wr.WriteEndElement()
        wr.WriteStartElement("ptoEmi")
        wr.WriteString(p_fact)
        wr.WriteEndElement()
        wr.WriteStartElement("secuencial")
        wr.WriteString(secuencial_fact)
        wr.WriteEndElement()
        wr.WriteStartElement("dirMatriz")
        wr.WriteString(datosfact("dirMatriz").ToString())
        wr.WriteEndElement()
        wr.WriteEndElement()
        wr.WriteStartElement("infoNotaCredito")
        wr.WriteStartElement("fechaEmision")
        wr.WriteString(datosfact("fecha_emision").ToString().Substring(0, 10))
        wr.WriteEndElement()
        wr.WriteStartElement("dirEstablecimiento")
        wr.WriteString(datosfact("dirEstablecimiento").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("tipoIdentificacionComprador")
        wr.WriteString(datosfact("cod_responsable").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("razonSocialComprador")
        wr.WriteString(datosfact("cod_responsable").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("identificacionComprador")
        wr.WriteString(datosfact("cod_responsable").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("contribuyenteEspecial")
        wr.WriteString(datosfact("cod_ruc").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("obligadoContabilidad")
        wr.WriteString(datosfact("cod_ruc").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("codDocModificado")
        wr.WriteString("01")
        wr.WriteEndElement()
        wr.WriteStartElement("numDocModificado")
        wr.WriteString(datosfact("num_establecimiento_dm").ToString() & "-" + datosfact("punto_facturacion_dm").ToString() & "-" + datosfact("secuencial_dm").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("fechaEmisionDocSustento")
        wr.WriteString(datosfact("fecha_emision_dm").ToString().Substring(0, 10))
        wr.WriteEndElement()
        wr.WriteStartElement("totalSinImpuestos")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosfact("total_sinImpuesto").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("valorModificacion")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosfact("valorTotal").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("moneda")
        wr.WriteString("DOLAR")
        wr.WriteEndElement()
        wr.WriteStartElement("totalConImpuestos")
        SumTipoImpuestoIVANC(wr, num_estab_fact, p_fact, secuencial_fact, datosdetfact)
        wr.WriteEndElement()
        wr.WriteStartElement("motivo")
        wr.WriteString(datosfact("motivo").ToString())
        wr.WriteEndElement()
        wr.WriteEndElement()
        wr.WriteStartElement("detalles")
        CreaDetalleNotaCredito(wr, num_estab_fact, p_fact, secuencial_fact, datosdetfact)
        wr.WriteEndElement()
        wr.WriteStartElement("infoAdicional")
        wr.WriteStartElement("campoAdicional")
        wr.WriteStartAttribute("nombre")
        wr.WriteString("Dirección: ")
        wr.WriteEndAttribute()
        wr.WriteString(datosfact("cod_responsable").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("campoAdicional")
        wr.WriteStartAttribute("nombre")
        wr.WriteString("Teléfono: ")
        wr.WriteEndAttribute()
        wr.WriteString(datosfact("cod_responsable").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("campoAdicional")
        wr.WriteStartAttribute("nombre")
        wr.WriteString("E-mail: ")
        wr.WriteEndAttribute()
        wr.WriteString(datosfact("cod_responsable").ToString())
        wr.WriteEndElement()
        wr.WriteEndElement()
      End While

      wr.WriteEndElement()
      wr.WriteEndDocument()
      wr.Close()
    End Sub

    Public Sub SumTipoImpuestoIVANC(ByVal wr As XmlTextWriter, ByVal num_estab_fact As String, ByVal p_fact As String, ByVal secuencial_fact As String, ByVal datosdetfact As DataTableReader)
      While datosdetfact.Read()
        wr.WriteStartElement("totalImpuesto")
        wr.WriteStartElement("codigo")
        wr.WriteString("2")
        wr.WriteEndElement()
        wr.WriteStartElement("codigoPorcentaje")
        wr.WriteString(datosdetfact("cod_tarifa_iva").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("baseImponible")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("baseImponible").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("valor")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("valoriva12").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteEndElement()
      End While
      datosdetfact.Close()
    End Sub

    Public Sub CreaDetalleNotaCredito(ByVal wr As XmlTextWriter, ByVal num_estab_fact As String, ByVal p_fact As String, ByVal secuencial_fact As String, ByVal datosdetfact As DataTableReader)
      While datosdetfact.Read()
        wr.WriteStartElement("detalle")
        wr.WriteStartElement("codigoInterno")
        wr.WriteString(datosdetfact("cod_item").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("codigoAdicional")
        wr.WriteString(datosdetfact("cod_auxiliar").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("descripcion")
        wr.WriteString(datosdetfact("descripcion").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("cantidad")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("cantidad").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("precioUnitario")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("valor_unitario").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("descuento")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("descuento").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("precioTotalSinImpuesto")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("subtotal_0").ToString()) + Convert.ToDouble(datosdetfact("subtotal_12").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        If datosdetfact("descripcion2").ToString() <> String.Empty OrElse datosdetfact("descripcion3").ToString() <> String.Empty Then
          wr.WriteStartElement("detallesAdicionales")
          If datosdetfact("descripcion2").ToString() <> String.Empty Then
            wr.WriteStartElement("detAdicional")
            wr.WriteStartAttribute("nombre")
            wr.WriteString(datosdetfact("descripcion2").ToString())
            wr.WriteStartAttribute("valor")
            wr.WriteString("Detalle1")
            wr.WriteEndAttribute()
            wr.WriteEndElement()
          End If

          If datosdetfact("descripcion3").ToString() <> String.Empty Then
            wr.WriteStartElement("detAdicional")
            wr.WriteStartAttribute("nombre")
            wr.WriteString(datosdetfact("descripcion3").ToString())
            wr.WriteStartAttribute("valor")
            wr.WriteString("Detalle2")
            wr.WriteEndAttribute()
            wr.WriteEndElement()
          End If

          wr.WriteEndElement()
        End If

        wr.WriteStartElement("impuestos")
        wr.WriteStartElement("impuesto")
        wr.WriteStartElement("codigo")
        wr.WriteString(datosdetfact("cod_iva").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("codigoPorcentaje")
        wr.WriteString(datosdetfact("cod_tarifa_iva").ToString())
        wr.WriteEndElement()
        wr.WriteStartElement("tarifa")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("valor").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("baseImponible")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("subtotal_0").ToString()) + Convert.ToDouble(datosdetfact("subtotal_12").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteStartElement("valor")
        wr.WriteString(String.Format("{0:0.00}", Convert.ToDouble(datosdetfact("iva_12").ToString())).Replace(",", "."))
        wr.WriteEndElement()
        wr.WriteEndElement()
        wr.WriteEndElement()
        wr.WriteEndElement()
      End While
    End Sub

  End Class
End Namespace

